In [1]:
a=10
b=20
c=a+b
print(c)


30


In [2]:
print('hello world')

hello world


In [7]:
print(a)

100


In [6]:
a=100

In [11]:
# Conditional Slicing on Arrays


In [2]:
import numpy as np
height = [1.87, 1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

arr_height = np.array(height)
arr_weight = np.array(weight)

bmi = arr_weight / arr_height **2



In [3]:
bmi[[False, True, True, True, False, True]]


array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [7]:
bmi>=25

array([False,  True,  True,  True, False,  True])

In [8]:
(bmi>25) & (bmi<28)

array([False,  True, False,  True, False,  True])

In [9]:
bmi[(bmi>25) & (bmi<28)]

array([27.88755755, 25.48723993, 25.84368152])

In [4]:
# important to note below, sum here returns total amount of elements in list
sum((bmi>25) & (bmi<28))

3

In [5]:
# sum below will return total sum of numbers
bmi.sum()


155.1958924497996

In [6]:
np.sum(bmi)

155.1958924497996

In [7]:
bmi.sum()

155.1958924497996

In [8]:
# the dir functions allow you to see all the functions available to you in jupter  
# __builtin__
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [12]:
#### Conditional Slicing for index positions

In [15]:
np.where(bmi>25, 'x', 'y') # return x if condition is satisfied, return y if condition is NOT satisfied

array(['y', 'x', 'x', 'x', 'y', 'x'], dtype='<U1')

In [16]:
np.where(bmi>25) # give you the index positions that satisfy the condition

(array([1, 2, 3, 5]),)

In [17]:
bmi[np.where(bmi>25)] # this returns the values that satify the conditions

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [18]:
### Slicing based on multipl econditions

In [28]:
arr = np.array([1,2,3,4,5,2,5,67,8,0,4,3,2,6,7,8,44,4,42])

arr1 = np.select([(arr%5==0), (arr%4==0)], ['divisible by 5', 'divisible by 4'], default='invalid')

# this arr1 will replace everything divisible by 5, with that text, same with 4, and then the rest that don't pass that test are replaced with invalid

In [29]:
indx = np.where(arr1!='invalid') 
# here we are selecting any instance in the result where they where not invalid

In [30]:
arr[indx] # now this will spit out all the arrays 

array([ 4,  5,  5,  8,  0,  4,  8, 44,  4])

In [ ]:
### Important Special Methods
1. np.arange(start, end+1, step)
2. np.reshape((rows, columns))
3. np.ravel(arr)
4. np.full()
5. np.zeros()
6. np.ones()
7. np.empty()
8. np.copy()

In [36]:
# np.arange(start, end+1, step)
arr = np.arange(1.2,10.5, 1.34) # just like python range, start, finish, then increment by
arr = np.arange(1, 10, 2)
arr


array([1, 3, 5, 7, 9])

In [38]:
# np.reshape((nrows, ncols))
arr = np.arange(1,13)
print(arr)
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [39]:
arr.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
arr.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr.reshape((2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
## 1020pm on instructors where i left off