In [4]:
import numpy as np

In [5]:
arr = np.array([[2,4],[3,2]])

In [6]:
arr

array([[2, 4],
       [3, 2]])

In [7]:
arr.min()

2

In [8]:
arr.max()

4

In [9]:
arr.argmin()

0

In [10]:
arr.sum() # sums up all the elements in the array

11

In [11]:
# Row-rise addition 
arr.sum(axis=0)

array([5, 6])

In [12]:
# Column-wise addition
arr.sum(axis=1)

array([6, 5])

In [13]:
# To get the list of all possible parameters inside Jupyter for a function, type 'shift-tab' and it will display the list of items available

In [14]:
# sum() gives you the sum of all the elements, size() gives you total amount of elements
arr.sum()/arr.size # gives you the average

2.75

In [16]:
# easier way to get average (the mean):
arr.mean()

2.75

In [30]:
arr2 = np.array([1,1,1,2,2,3,3,3,3,4,4,5,6,1000])

In [19]:
arr2.sum()

38

In [31]:
arr2.size

14

In [32]:
arr2.sum()/arr2.size

74.14285714285714

In [34]:
np.median(arr2)

3.0

In [45]:
arr3 = np.array([1,1,1,2,2,3,3,3,3,4,4,5,6])

In [39]:
np.mean(arr3) 

2.923076923076923

In [46]:
np.sqrt(arr3.var())

1.4915938022819473